title: Agricultural Consulting
email: davidjdebonis@gmail.com
description: let's answer the question: 'what is agricultural consulting?'
baseurl: ""
url: ""
github_username: djdebonis
twitter_username: davidjdebonis



theme: jekyll-theme-slate
